import type { Metadata } from "next";
import { Carter_One } from "next/font/google";
import "./globals.css";

import { Provider } from "@/providers/ChakraProvider";

const carter = Carter_One({ weight: ["400"], subsets: ["latin"] });

export const metadata: Metadata = {
      title: "Create Next App",
      description: "Generated by create next app",
};

export default function RootLayout({
      children,
}: Readonly<{
      children: React.ReactNode;
}>) {
      return (
            <html lang="en">
                  <body className={carter.className}>
                        <Provider>{children}</Provider>
                  </body>
            </html>
      );
}
